const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom');
const source=n=>fs.readFileSync(path.join(__dirname,'../src/shared/'+n),'utf8');
const turn=()=>new Promise(resolve=>setImmediate(resolve));
test('early bridge disconnects only marked DD handles, including parser/dynamic additions',async()=>{
 const dom=new JSDOM('<p id="other" data-w-id="other-animation">Other</p>',{runScripts:'outside-only'}),w=dom.window;
 try{w.eval(source('dd-bootstrap.js'));const p=w.document.createElement('p');p.setAttribute('data-tdb-dd-legacy','');p.setAttribute('data-w-id','old-dd');p.textContent='Keep this node';w.document.body.append(p);await turn();assert.equal(p.getAttribute('data-w-id'),null);assert.equal(p.dataset.tdbDdPreviousId,'old-dd');assert.equal(w.document.getElementById('other').getAttribute('data-w-id'),'other-animation');assert.equal(w.document.body.lastChild,p);assert.equal(p.textContent,'Keep this node');p.setAttribute('data-w-id','old-dd_instance-copy');await turn();assert.equal(p.getAttribute('data-w-id'),null);}finally{w.TDBDDFades?.destroy();w.close();}
});
test('page mounts share motion, leave gated components alone, and clean up removed nodes',async()=>{
 const dom=new JSDOM('<p data-tdb-dd-page="native" data-tdb-dd-preset="orange">Native</p><p data-tdb-dd-text>Gated</p><p data-tdb-dd-legacy data-w-id="still-owned" data-tdb-dd-page="native">No competing owner</p><dialog class="tdbc-dialog"><p class="tdbc-dd-fade">Heading</p><footer class="tdbc-section-footer"><p class="tdbc-dd-fade">Always opaque</p></footer></dialog>',{runScripts:'outside-only',url:'https://dentalbarns.webflow.io/'}),w=dom.window;
 try{const script=w.document.createElement('script');script.src='https://cdn.jsdelivr.net/gh/TheDentalBarns/tdb-webflow-runtime@test/dist/tdb-dd-loader.js';Object.defineProperty(w.document,'currentScript',{value:script});const mounted=[];let removed=0;w.TDBModules={load:async()=>{}};w.TDBMotion={ddRegion(){},ddText(nodes,options){mounted.push({node:nodes[0],options});return{destroy(){removed++;}};}};w.eval(source('dd-loader.js'));await turn();await turn();assert.equal(mounted.length,2);assert.equal(mounted[0].options.preset,'orange');assert.equal(mounted[1].options.root,w.document.querySelector('dialog'));const newNode=w.document.createElement('p');newNode.setAttribute('data-tdb-dd-page','viewport');w.document.body.append(newNode);await turn();await turn();assert.equal(mounted.length,3);newNode.remove();await turn();await turn();assert.equal(removed,1);assert.equal(w.TDBDDFades.count(),2);}finally{w.TDBDDFades?.destroy();w.close();}
});
