const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require('jsdom');
test('independent accessible accordions tolerate rapid reversals and repeated mounting', () => {
  const dom = new JSDOM('<div id="a" data-tdb-disclosure-trigger role="button" tabindex="0" aria-expanded="false" aria-controls="ap"></div><div id="ap" data-tdb-disclosure-panel hidden></div><button id="b" data-tdb-disclosure-trigger aria-expanded="false" aria-controls="bp"></button><div id="bp" data-tdb-disclosure-panel hidden></div>', { runScripts: 'outside-only' });
  const w = dom.window, d = w.document;
  w.eval(fs.readFileSync('src/shared/disclosure.js', 'utf8'));
  w.TDBDisclosure.refresh(); w.TDBDisclosure.refresh();
  const a = d.getElementById('a'), ap = d.getElementById('ap'), b = d.getElementById('b'), bp = d.getElementById('bp');
  a.dispatchEvent(new w.KeyboardEvent('keydown', {key:'Enter', bubbles:true, cancelable:true}));
  assert.equal(ap.hidden, false); assert.equal(ap.inert, false);
  b.click(); assert.equal(bp.hidden, false); assert.equal(ap.hidden, false);
  for (let n=0; n<20; n++) a.click();
  assert.equal(a.getAttribute('aria-expanded'), 'true');
  const held = new w.KeyboardEvent('keydown', {key:' ', repeat:true, cancelable:true});
  a.dispatchEvent(held); assert.equal(held.defaultPrevented, true); assert.equal(ap.hidden, false);
  a.dispatchEvent(new w.KeyboardEvent('keydown', {key:' ', cancelable:true}));
  assert.equal(ap.hidden, true); assert.equal(ap.inert, true); assert.equal(bp.hidden, false);
  dom.window.close();
});

test('copied components pair locally, get unique IDs and return focus before closing', () => {
  const row = '<div data-tdb-disclosure-item><button id="question" data-tdb-disclosure-trigger aria-controls="answer" aria-expanded="false">Question</button><div id="answer" data-tdb-disclosure-panel hidden><a href="#example">Answer link</a></div></div>';
  const dom = new JSDOM(row + row, { runScripts: 'outside-only' });
  const w = dom.window, d = w.document;
  w.eval(fs.readFileSync('src/shared/disclosure.js', 'utf8'));
  w.TDBDisclosure.refresh();
  const [first, second] = d.querySelectorAll('button');
  const [a, b] = d.querySelectorAll('[data-tdb-disclosure-panel]');
  assert.notEqual(first.id, second.id);
  assert.notEqual(a.id, b.id);
  assert.equal(second.getAttribute('aria-controls'), b.id);
  assert.equal(b.getAttribute('aria-labelledby'), second.id);
  second.click();
  assert.equal(a.hidden, true);
  assert.equal(b.hidden, false);
  b.firstElementChild.focus();
  w.TDBDisclosure.mount(second).set(false);
  assert.equal(d.activeElement, second);
  assert.equal(b.getAttribute('aria-hidden'), 'true');
  w.TDBDisclosure.mount(second).destroy();
  w.TDBDisclosure.refresh(second);
  second.click();
  assert.equal(b.hidden, false);
  w.close();
});
