/* Staging footer regression: set TDB_REVIEW_SOURCE to preview local runtime. */
const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
(async()=>{
const b=await chromium.launch({executablePath:process.env.TDB_CHROMIUM,proxy:process.env.HTTPS_PROXY?{server:process.env.HTTPS_PROXY}:undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
try{const c=await b.newContext({ignoreHTTPSErrors:true,viewport:{width:375,height:667},isMobile:true,hasTouch:true});const url='https://dentalbarns.webflow.io/';await c.addCookies([{name:'CookieScriptConsent',value:encodeURIComponent(JSON.stringify({action:'reject',categories:[]})),url}]);
await c.route('**/*',r=>{const u=new URL(r.request().url());if(process.env.TDB_REVIEW_SOURCE&&u.pathname.endsWith('/tdb-reviews.js'))return r.fulfill({contentType:'application/javascript',body:fs.readFileSync(process.env.TDB_REVIEW_SOURCE,'utf8')});return ['dentalbarns.webflow.io','cdn.prod.website-files.com','cdn.jsdelivr.net','fonts.googleapis.com','fonts.gstatic.com','d3e54v103j8qbb.cloudfront.net'].includes(u.hostname)?r.continue():r.abort()});
const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.TDBReviewLoader);await p.evaluate(async()=>{await TDBReviewLoader.prepare();await TDBReviewLoader.open({trigger:document.querySelector('[data-tdb-review-introduction]')})});await p.locator('[data-tdb-filter-toggle]').click();await p.waitForFunction(()=>document.querySelector('[data-tdb-filter-apply]').getAttribute('aria-busy')==='false');await p.evaluate(()=>document.fonts.ready);console.log('runtime',await p.evaluate(()=>TDBReviews.version));
const matrix=[];
for(const [width,height] of [[320,568],[360,640],[375,667],[390,844],[414,896],[479,800],[568,320],[667,375],[844,390],[1024,768],[1440,900],[375,667]]){
await p.setViewportSize({width,height});await p.waitForTimeout(180);
for(const count of ['85','888']){
await p.evaluate(count=>{document.querySelector('[data-tdb-filter-count-reserve]').textContent=count;document.querySelector('[data-tdb-filter-apply-count] .review-number_value').textContent=count;},count);await p.waitForTimeout(50);
const g=await p.evaluate(()=>{const a=document.querySelector('[data-tdb-filter-apply]'),x=document.querySelector('.is-filter-floating'),word=document.querySelector('[data-tdb-filter-apply-plural]').parentElement;const rect=a.getBoundingClientRect(),xr=x.getBoundingClientRect(),font=getComputedStyle(a).fontSize,hidden=word.hidden,pad=a.style.cssText;word.hidden=false;a.style.removeProperty('padding-left');a.style.removeProperty('padding-right');const baseline=a.getBoundingClientRect(),originalX=x.getBoundingClientRect().toJSON();const result={gap:rect.left-xr.right,hidden,height:rect.height,baseHeight:baseline.height,font,baseFont:getComputedStyle(a).fontSize,baseGap:baseline.left-xr.right,x:xr.toJSON(),originalX};word.hidden=hidden;a.style.cssText=pad;return result;});
assert(g.gap>=11.99,JSON.stringify({width,height,count,g}));assert.equal(g.height,g.baseHeight);assert.equal(g.font,g.baseFont);assert.deepEqual(g.x,g.originalX);assert.equal(g.hidden,g.baseGap<12);matrix.push({width,height,count,gap:+g.gap.toFixed(2),short:g.hidden});
}
}
console.log(JSON.stringify(matrix));
await p.evaluate(()=>{window.countNode=document.querySelector('[data-tdb-filter-apply-count]');window.countAnims=0;const animate=countNode.animate;countNode.animate=function(...args){countAnims++;return animate.apply(this,args)};});
console.log('options',await p.locator('[data-tdb-filter-disclosure]').evaluateAll(ns=>ns.map(n=>n.dataset.tdbFilterDisclosure)));
await p.locator('[data-tdb-filter-disclosure="platform"]').click();await p.locator('[data-tdb-filter-group="platform"][data-tdb-filter-value="Google"]').click();await p.waitForFunction(()=>document.querySelector('[data-tdb-filter-apply]').getAttribute('aria-busy')==='false');console.log('filtered',await p.locator('[data-tdb-filter-apply]').getAttribute('aria-label'));assert(await p.evaluate(()=>countNode===document.querySelector('[data-tdb-filter-apply-count]')));
await p.locator('[data-tdb-filter-apply]').click();await p.waitForFunction(()=>document.querySelector('[data-tdb-filter-toggle]').getAttribute('aria-expanded')==='false');await p.locator('[data-tdb-filter-toggle]').click();await p.locator('[data-tdb-filter-reset]').click();await p.waitForFunction(()=>document.querySelector('[data-tdb-filter-apply]').getAttribute('aria-label')==='View 85 reviews'&&document.querySelector('[data-tdb-filter-apply]').getAttribute('aria-busy')==='false');await p.locator('.is-filter-floating').click();await p.waitForFunction(()=>document.querySelector('[data-tdb-filter-toggle]').getAttribute('aria-expanded')==='false');assert.deepEqual(errors,[]);console.log('PASS hit-box clearance, original X geometry, height/font, wider label restoration, three-digit reserve, filtering/apply/reset/X, retained ticker node, no browser errors');
}finally{await b.close()}
})().catch(e=>{console.error(e);process.exit(1)});
