const assert=require('assert/strict'),fs=require('fs'),{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});try{
const p=await b.newPage();await p.route('https://fixture.test/**',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><body></body></html>'}));await p.goto('https://fixture.test/');await p.addScriptTag({content:fs.readFileSync(require('path').join(__dirname,'../src/reviews/native/cms.js'),'utf8')});
const result=await p.evaluate(async()=>{
 const requests=[],count=108;let inflight=0,max=0,fail=false;
 const meta=i=>`<div data-tdb-review-index-record data-review-slug="r-${i}" data-review-platform-2="Google" data-review-star-rating="${i===107?1:5}" data-review-review-date="2026-09-01"><span data-tdb-review-flag="topic-veneers"></span><span data-tdb-review-flag="topic-${i%2?'invisalign':'clear-aligners'}"></span></div>`;
 const record=i=>`<article data-tdb-review-record data-review-slug="r-${i}" data-review-platform-2="Google" data-review-star-rating="${i===107?1:5}" data-tdb-review-detail="v1"><h1 data-tdb-review-field="reviewer-display-name">Person ${i}</h1><div data-tdb-review-field="full-review">Review text ${i}</div><span data-tdb-review-flag="exclude-from-display" class="w-condition-invisible"></span></article>`;
 const feed=(page=1)=>`<div data-tdb-review-cms="v1">${Array.from({length:20},(_,i)=>record(i)).join('')}<a class="w-pagination-next" href="?body_page=2"></a></div><div data-tdb-review-index="v1">${Array.from({length:page===1?100:8},(_,i)=>meta(i+(page===1?0:100))).join('')}${page===1?'<a class="w-pagination-next" href="?index_page=2"></a>':''}</div><div data-tdb-review-aggregate data-review-average="4.95" data-review-total="108"></div><div data-tdb-review-response-record data-review-slug="r-107"><div data-tdb-review-response>Original CMS response</div></div>`;
 window.fetch=async(url,{signal}={})=>{requests.push(url);inflight++;max=Math.max(max,inflight);try{await new Promise((resolve,reject)=>{const timer=setTimeout(resolve,8);signal?.addEventListener('abort',()=>{clearTimeout(timer);reject(new DOMException('Aborted','AbortError'))},{once:true});});if(fail&&url.endsWith('/r-99'))return new Response('',{status:503});return new Response(url.includes('/review-topics/')?record(+url.split('-').at(-1)):feed(url.includes('index_page=2')?2:1));}finally{inflight--;}};
 const d=await TDBReviewCMS.load();await d.loadIndex();const initialRequests=requests.length;
 const ids=Array.from({length:20},(_,i)=>'r-'+(i+10));const batch=await d.fetchRecords(ids);const afterBatch=requests.length;
 await d.fetchRecords(ids);const afterRepeat=requests.length;
 const concurrentBefore=requests.length;await Promise.all([d.fetchRecords(['r-50','r-51']),d.fetchRecords(['r-50','r-51'])]);const concurrent=requests.length-concurrentBefore;
 const low=await d.fetchRecords(['r-107']);fail=true;let failed=false;try{await d.fetchRecords(['r-99'])}catch{failed=true;}fail=false;const retry=await d.fetchRecords(['r-99']);
 const c=new AbortController();const flight=d.fetchRecords(['r-90','r-91','r-92','r-93','r-94'],{signal:c.signal});c.abort();let cancelled=false;try{await flight}catch(e){cancelled=e.name==='AbortError'};
 let outside=false;try{await d.fetchRecords(['not-listed'])}catch{outside=true;}
 return{alias:d.filterIndex.every(r=>r.topics.includes('clear-aligners')&&!r.topics.includes('invisalign')),sameContext:TDBReviewCMS.contextForPath('/treatments/invisalign')===TDBReviewCMS.contextForPath('/treatments/clear-aligners'),index:d.filterIndex.length,ready:d.indexReady,initialRequests,afterBatch,afterRepeat,batch:batch.length,concurrent,response:low[0].response,failed,retry:retry[0].id,cancelled,outside,max};
});assert(result.alias&&result.sameContext);assert.equal(result.index,108);assert.equal(result.initialRequests,2);assert.equal(result.afterBatch,12);assert.equal(result.afterRepeat,12);assert.equal(result.concurrent,2);assert.equal(result.response,'Original CMS response');assert(result.failed&&result.cancelled&&result.outside);assert.equal(result.retry,'r-99');assert(result.max<=4);console.log('PASS',result);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
