const fs=require('fs'),assert=require('assert/strict'),{JSDOM}=require('jsdom');
const code=fs.readFileSync(__dirname+'/../src/reviews/native/loader.js','utf8');
const tick=()=>new Promise(r=>setTimeout(r,0));
const flush=async()=>{await tick();await tick();await tick()};
function setup(markup){const dom=new JSDOM(`<script src="https://cdn.jsdelivr.net/gh/TheDentalBarns/tdb-webflow-runtime@test/dist/tdb-reviews-loader.js"></script>${markup}`,{url:'https://dentalbarns.webflow.io/',runScripts:'outside-only'});const w=dom.window,loads=[],mounts=[],observers=[];let permission=false,sync;Object.defineProperty(w.document,'currentScript',{value:w.document.querySelector('script')});w.IntersectionObserver=class{constructor(fn){this.fn=fn;observers.push(this)}observe(){}unobserve(){}};w.TDBReviewOptions={permission:()=>permission,subscribe:fn=>sync=fn};w.TDBModules={load:async u=>loads.push(u.pathname.split('/').pop())};w.TDBReviewCMS={load:async()=>({records:[],featured:[],total:85,average:4.94,ensureIdentity:async()=>{},ensure:async()=>{},loadAll:async()=>{}})};const plugins=new Map();w.TDBSwiper={create(){},register:(name,plugin)=>plugins.set(name,plugin),mount:(name,...args)=>{mounts.push('plugin '+name);return plugins.get(name).mount(...args)}};for(const [name,type] of [['TDBReviewIntroduction','intro'],['TDBReviewCards','cards'],['TDBReviewQuotes','quotes'],['TDBReviews','drawer']])w[name]={mount(root){mounts.push(type);return{destroy(){mounts.push('destroy '+type)}}}};w.eval(code);w.document.dispatchEvent(new w.Event('DOMContentLoaded'));return{w,loads,mounts,near(selector='[data-tdb-review-introduction]'){observers[0].fn([{target:w.document.querySelector(selector),isIntersecting:true}])},permit(v){permission=v;sync()},close(){dom.window.close()}}}
(async()=>{const t=setup('<section data-tdb-review-introduction></section><section data-tdb-review-cards></section>');t.near();await tick();assert.equal(t.loads.length,0);t.permit(true);await tick();await tick();assert.deepEqual(t.mounts,['intro']);assert(t.loads.includes('tdb-review-introduction.js'));assert(!t.loads.includes('tdb-review-cards.js'));assert(!t.loads.some(n=>n.includes('swiper')),'No drawer/slider means no Swiper');t.permit(true);await tick();assert.deepEqual(t.mounts,['intro']);t.permit(false);assert.deepEqual(t.mounts,['intro','destroy intro']);t.permit(true);await tick();await tick();assert.deepEqual(t.mounts,['intro','destroy intro','intro']);t.close();const absent=setup('');absent.permit(true);await tick();assert.equal(absent.loads.length,0);await assert.rejects(absent.w.TDBReviewLoader.prepare({}),/No review component/);absent.close();
const cards=setup('<section data-tdb-review-cards></section><div data-tdb-reviews></div>');cards.near('[data-tdb-review-cards]');cards.permit(true);await flush();assert.deepEqual(cards.mounts,['plugin review-cards','cards']);assert(!cards.loads.includes('tdb-reviews.js'),'nearby cards do not prepare the drawer');await cards.w.TDBReviewLoader.prepare();assert.deepEqual(cards.mounts,['plugin review-cards','cards','plugin review-drawer','drawer']);assert(cards.loads.includes('tdb-swiper-8.4.7.min.js'));assert(!cards.loads.includes('tdb-review-quotes.js'));cards.permit(true);await flush();assert.equal(cards.mounts.length,4);cards.permit(false);assert.deepEqual(cards.mounts.slice(-2),['destroy drawer','destroy cards']);cards.close();
const introWithDrawer=setup('<section data-tdb-review-introduction></section><div data-tdb-reviews></div>');introWithDrawer.near();introWithDrawer.permit(true);await flush();assert.deepEqual(introWithDrawer.mounts,['intro']);assert(!introWithDrawer.loads.some(n=>n.includes('swiper')),'nearby introduction with a drawer does not download its engine');assert(!introWithDrawer.loads.includes('tdb-reviews.js'));introWithDrawer.close();
const quotes=setup('<section><div data-tdb-review-quotes></div></section>');quotes.near('[data-tdb-review-quotes]');quotes.permit(true);await flush();assert.deepEqual(quotes.mounts,['plugin review-testimonials','quotes']);assert(!quotes.loads.includes('tdb-reviews.js'));assert(!quotes.loads.includes('tdb-review-cards.js'));quotes.close();console.log('PASS: permission, presence, per-component code, optional Swiper, duplicate prevention and regrant');})().catch(e=>{console.error(e);process.exitCode=1});
