const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const source=fs.readFileSync(path.join(__dirname,'../dist/tdb-modules.js'),'utf8');
const base='https://cdn.jsdelivr.net/gh/TheDentalBarns/tdb-webflow-runtime@';
function setup(native){const scripts=[],window={};class Script extends EventTarget{constructor(){super();this.dataset={};this.attrs={};}setAttribute(k,v){this.attrs[k]=v}remove(){scripts.splice(scripts.indexOf(this),1)}}const document={scripts,querySelector(selector){if(selector==='script[data-tdb-reviews-loader][src]')return native?{src:base+'new/dist/tdb-reviews-loader.js'}:null;return scripts.find(s=>Object.hasOwn(s.attrs,selector.slice(7,-1)));},createElement(){return new Script()},head:{append(s){scripts.push(s)}}};vm.runInNewContext(source,{window,document,URL,location:{href:'https://dentalbarns.webflow.io/'},setTimeout,clearTimeout});return{window,scripts,load:window.TDBModules.load,finish(){scripts.forEach(s=>s.dispatchEvent(new Event('load')))}}}
(async()=>{
 for(const file of ['tdb-motion.js','tdb-swiper-8.4.7.min.js'])for(const reverse of [false,true]){const t=setup(true);assert.equal(t.scripts.length,0);const urls=[base+'old/dist/'+file,base+'new/dist/'+file];if(reverse)urls.reverse();const a=t.load(urls[0]),b=t.load(urls[1]);assert.equal(a,b);assert.equal(t.scripts.length,1);assert.equal(t.scripts[0].src,base+'new/dist/'+file);t.finish();await a;}
 {const t=setup(false),a=t.load(base+'old/dist/tdb-motion.js');assert.equal(t.scripts[0].src,base+'old/dist/tdb-motion.js');t.finish();await a;}
 {const t=setup(true);t.window.Swiper=function(){};const a=t.load(base+'old/dist/tdb-swiper-8.4.7.min.js',{ready:()=>!!t.window.Swiper});assert.equal(t.scripts.length,1,'engine without TDB adapter cannot satisfy the dependency');t.finish();await a;}
 {const t=setup(true);const failed=t.load(base+'old/dist/tdb-motion.js');t.scripts[0].dispatchEvent(new Event('error'));await assert.rejects(failed);assert.equal(t.scripts.length,0);const retry=t.load(base+'new/dist/tdb-motion.js');assert.equal(t.scripts.length,1);t.finish();await retry;}
 console.log('PASS: shared motion/engine request identity in both orders, lazy definitions, legacy-page pins, adapter readiness, failed-request retry.');
})().catch(e=>{console.error(e);process.exitCode=1});
