/* Single source-to-output manifest for local and CI runtime builds. */
module.exports = {
  'dist/tdb-immediate-runtime-batch.min.js': ['src/runtime/immediate-runtime-batch.js'],
  'dist/tdb-modules.js': ['src/shared/modules.js'],
  'dist/tdb-gallery.js': ['src/sliders/gallery-presentation.js', 'src/sliders/gallery-plugin.js'],
  'dist/tdb-parallax.js': ['src/sliders/treatment-plugin.js', 'src/sliders/parallax-plugin.js'],
  'dist/tdb-reviews.js': ['src/reviews/native/drawer-content.js'],
  'dist/tdb-review-cards.js': ['src/reviews/native/cards.js'],
  'dist/tdb-vip-form.js': ['src/forms/vip-form.js'],
  'dist/tdb-five-senses-loader.js': ['src/five-senses/loader.js'],
  'dist/tdb-five-senses.js': ['src/five-senses/scene-renderer.js', 'src/five-senses/five-senses.js'],
  'dist/tdb-quote-carousel.js': ['src/team-quotes/team-quotes.js'],
  'dist/tdb-quote-carousel.min.js': ['src/team-quotes/team-quotes.js'],
  'dist/tdb-drawer.js': ['src/shared/scroll-lock.js', 'src/shared/site-chrome.js',
    'src/shared/carousel-controls.js', 'src/shared/drawer-reading.js', 'src/shared/drawer.js'],
  'dist/tdb-footer-runtime.min.js': ['src/runtime/initial-position.js', 'src/runtime/home-anchor-settlement.js', 'src/banner/loader.js',
    'src/vip-drawer/vip-focus.js', 'src/runtime/deferred-ui.js', 'src/runtime/site-asset-loader.js'],
  'dist/tdb-vip-drawer.js': ['src/shared/panel-motion.js', 'src/vip-drawer/vip-drawer.js'],
  'dist/tdb-logo-marquee.min.js': ['src/logo-marquee/logo-marquee.js'],
  'dist/tdb-usp-drawer.js': ['src/usp/drawer.js'],
  'dist/tdb-usp-loader.js': ['src/usp/loader.js'],
  'dist/tdb-consent-startup.min.js': ['src/shared/scroll-lock.js', 'src/consent/banner.js'],
  'dist/tdb-navbar-loader.js': ['src/navbar/navbar-state.js', 'src/shared/scroll-lock.js',
    'src/navbar/navbar-mobile-lock.js', 'src/navbar/navbar-loader.js'],
  'dist/tdb-navbar.min.js': ['src/shared/panel-motion.js', 'src/navbar/navbar-enhancement.js'],
};
