'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require('../../tools/runtime-tests/node_modules/jsdom');
const script=fs.readFileSync(require.resolve('../../src/vip-drawer/interest-defaults.js'),'utf8');
const values=['','Cosmetic Dentistry','Restorative Dentistry','Signature Assessment','Smile Design','Nervous Patient Care','Invisalign','Composite Bonding','Veneers','Whitening'];
async function setup(path){const dom=new JSDOM('<body>'+[1,2].map(()=>'<select name="Treatment-Of-Interest">'+values.map(v=>'<option value="'+v+'">'+v+'</option>').join('')+'</select>').join('')+'</body>',{url:'https://example.org'+path,runScripts:'outside-only'});dom.window.eval(script);await new Promise(r=>setImmediate(r));return dom;}
test('both forms receive the relevant service or treatment default',async()=>{
 for(const [path,value] of [['/services/cosmetic-dentist','Cosmetic Dentistry'],['/services/general-dentistry','Restorative Dentistry'],['/services/fast-track','Signature Assessment'],['/first-visit','Signature Assessment'],['/services/smile-design','Smile Design'],['/services/nervous-patient-care','Nervous Patient Care'],['/treatments/clear-aligners','Invisalign'],['/areas/sutton-coldfield-composite-bonding','Composite Bonding'],['/treatments/veneers','Veneers'],['/treatments/teeth-whitening','Whitening'],['/vip','']]){const dom=await setup(path);try{for(const field of dom.window.document.querySelectorAll('select'))assert.equal(field.value,value,path);}finally{dom.window.close();}}
});
test('calculator intent survives legacy drawer preselection and applies to inserted forms',async()=>{const dom=await setup('/treatments/invisalign');try{const w=dom.window;w.TDBVIPInterest.fromCalculator('Signature Assessment');const field=w.document.querySelector('select');field.value='Invisalign';field.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(field.value,'Signature Assessment');const clone=field.cloneNode(true);w.document.body.append(clone);await new Promise(r=>setImmediate(r));assert.equal(clone.value,'Signature Assessment');w.TDBVIPInterest.fromCalculator('Smile Design');for(const select of w.document.querySelectorAll('select'))assert.equal(select.value,'Smile Design');}finally{dom.window.close();}});
test('VIP fallback accepts only known interest values',async()=>{for(const [path,value] of [['/vip?interest=Smile%20Design','Smile Design'],['/vip?interest=Signature%20Assessment','Signature Assessment'],['/vip?interest=anything-else','']]){const dom=await setup(path);try{assert.equal(dom.window.document.querySelector('select').value,value);}finally{dom.window.close();}}});
