from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SOURCES = [
    ROOT / 'src/styles/tdb-elfsight-timer.css',
    ROOT / 'src/styles/tdb-vimeo-ui.css',
    ROOT / 'src/styles/tdb-runtime-ui.css',
    ROOT / 'src/styles/tdb-deferred-ui.css',
    ROOT / 'src/styles/tdb-slider-ui.css',
    ROOT / 'src/styles/tdb-vip-drawer-desktop.css',
]

HEADER = '''/* TDB consolidated non-critical UI stylesheet.\n * Generated by tools/build-ui.py — edit source modules, not this file.\n * Order: Elfsight, Vimeo, shared runtime, shared VIP/mobile overrides, slider UI, desktop VIP overrides.\n */\n\n'''


def read(path: Path) -> str:
    return path.read_text(encoding='utf-8').strip()


bundle = HEADER + '\n\n'.join(read(source) for source in SOURCES) + '\n'

for output in [ROOT / 'src/styles/tdb-ui.css', ROOT / 'dist/tdb-ui.css']:
    output.write_text(bundle, encoding='utf-8')

print(f'Built consolidated UI: {len(bundle)} bytes')
