from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

GLOBAL_SOURCES = [
    ROOT / 'src/styles/tdb-elfsight-timer.css',
    ROOT / 'src/styles/tdb-vimeo-ui.css',
    ROOT / 'src/styles/tdb-runtime-ui.css',
    ROOT / 'src/styles/tdb-deferred-ui.css',
    ROOT / 'src/styles/tdb-slider-focus.css',
]

VIP_SOURCES = [
    ROOT / 'src/styles/tdb-vip-drawer-shared.css',
    ROOT / 'src/styles/tdb-vip-drawer-desktop.css',
]

SLIDER_SOURCE = ROOT / 'src/styles/tdb-slider-ui.css'

GLOBAL_HEADER = '''/* TDB global non-critical UI stylesheet.\n * Generated by tools/build-ui.py — edit source modules, not this file.\n * Order: Elfsight, Vimeo, shared runtime, global deferred UI, shared slider focus.\n */\n\n'''
VIP_HEADER = '''/* TDB VIP drawer stylesheet.\n * Generated by tools/build-ui.py — loaded with the VIP runtime.\n */\n\n'''
SLIDER_HEADER = '''/* TDB slider UI stylesheet.\n * Generated by tools/build-ui.py — loaded on proximity/intent; ready before slider initialization.\n */\n\n'''


def read(path: Path) -> str:
    return path.read_text(encoding='utf-8').strip()


def write(path: Path, content: str) -> None:
    path.write_text(content, encoding='utf-8')


global_bundle = GLOBAL_HEADER + '\n\n'.join(read(source) for source in GLOBAL_SOURCES) + '\n'
vip_bundle = VIP_HEADER + '\n\n'.join(read(source) for source in VIP_SOURCES) + '\n'
slider_bundle = SLIDER_HEADER + read(SLIDER_SOURCE) + '\n'

write(ROOT / 'src/styles/tdb-ui.css', global_bundle)
write(ROOT / 'dist/tdb-ui.css', global_bundle)
write(ROOT / 'dist/tdb-vip.css', vip_bundle)
write(ROOT / 'dist/tdb-slider-ui.css', slider_bundle)

write(ROOT / 'dist/tdb-vimeo-content-ui.css', read(ROOT / 'src/styles/tdb-vimeo-content-ui.css') + '\n')

print(f'Built global UI: {len(global_bundle)} bytes')
print(f'Built VIP UI: {len(vip_bundle)} bytes')
print(f'Built slider UI: {len(slider_bundle)} bytes')
