from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SOURCES = [
    ROOT / 'src/styles/tdb-elfsight-timer.css',
    ROOT / 'src/styles/tdb-vimeo-ui.css',
    ROOT / 'src/styles/tdb-runtime-ui.css',
    ROOT / 'src/styles/tdb-deferred-ui.css',
    ROOT / 'src/styles/tdb-slider-ui.css',
    ROOT / 'src/styles/tdb-vip-drawer-desktop.css',
]

HEADER = '''/* TDB consolidated non-critical UI stylesheet.\n * Generated by tools/build-ui.py — edit source modules, not this file.\n * Order: Elfsight, Vimeo, shared runtime, deferred/VIP mobile, slider UI, VIP desktop.\n */\n\n'''


def read(path: Path) -> str:
    return path.read_text(encoding='utf-8').strip()


def normalize_deferred(css: str) -> str:
    # Preserve the approved visual refinements previously supplied as Webflow overrides.
    css = css.replace(
        'border-top: 1px solid rgba(255, 255, 255, 0.58);',
        'border-top: 0;',
        1,
    )
    old = '''  #tdb-vip-drawer .tdb-vip-drawer-arrow {\n    display: block;\n    flex: 0 0 auto;\n    width: 0.75rem;\n    height: 0.625rem;\n    margin-left: auto;\n    background: url('https://s3.amazonaws.com/webflow-prod-assets/677cf86cf9952f978d94d80c/678503c5b3e550705cf3f986_arrow.svg') center/contain no-repeat;\n    transform: rotate(-90deg);\n    transition: transform var(--tdb-vip-tab-duration) var(--tdb-vip-tab-ease);\n  }'''
    new = '''  #tdb-vip-drawer .tdb-vip-drawer-arrow {\n    display: block;\n    flex: 0 0 auto;\n    width: 1rem;\n    height: 1rem;\n    margin-left: auto;\n    background: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Cpath fill='%23ffffff' d='m18 6-1.43 1.393L24.15 15H4v2h20.15l-7.58 7.573L18 26l10-10z'/%3E%3C/svg%3E") center/contain no-repeat !important;\n    transform: rotate(-90deg);\n    transition: transform var(--tdb-vip-tab-duration) var(--tdb-vip-tab-ease);\n  }'''
    if old not in css:
        raise RuntimeError('Expected mobile VIP arrow block was not found')
    return css.replace(old, new, 1)


def normalize_desktop(css: str) -> str:
    # Desktop now shares the same borderless drawer presentation as mobile.
    return css.replace(
        'border-top: 1px solid rgba(255, 255, 255, 0.58);',
        'border-top: 0;',
        1,
    )


parts = []
for source in SOURCES:
    css = read(source)
    if source.name == 'tdb-deferred-ui.css':
        css = normalize_deferred(css)
    elif source.name == 'tdb-vip-drawer-desktop.css':
        css = normalize_desktop(css)
    parts.append(css)

bundle = HEADER + '\n\n'.join(parts) + '\n'

for output in [ROOT / 'src/styles/tdb-ui.css', ROOT / 'dist/tdb-ui.css']:
    output.write_text(bundle, encoding='utf-8')

print(f'Built consolidated UI: {len(bundle)} bytes')
